### ISSUE TITLE
Bug: 生成PDF文件时表格显示错误

### ISSUE THREAD

**Issue by YikeZhou** [BEATREE/typora-maize-theme#1]
表格中的代码不能正常显示。

Markdown源码：
```markdown
| 说明             | 左部               | 右部                                                         |
| ---------------- | ------------------ | ------------------------------------------------------------ |
| 编译单元         | `CompUnit`         | `Decl`<br />`FuncDef`<br />`CompUnit Decl`<br />`CompUnit FuncDef` |
| 声明             | `Decl`             | `ConstDecl`<br />`VarDecl`                                   |
```

Typora中显示基本正常，除了代码格式的边框有部分重合：

![Snipaste_2020-08-25_13-03-18](https://user-images.githubusercontent.com/43945722/91125091-7b56de80-e6d3-11ea-92da-142dc5447d83.png)

生成PDF后的显示变成了黑色：

![Snipaste_2020-08-25_13-04-00](https://user-images.githubusercontent.com/43945722/91125101-814cbf80-e6d3-11ea-8ddb-f2989082b9a0.png)

-----

第一次提issue，格式不正确之处请多包涵。

**Comment by BEATREE** [comment]
不好意思哈，刚看到通知。第一次收到issue😂，我看看是哪里的问题，稍等哈

**Comment by BEATREE** [comment]
Typora 设置默认行高，表格内两行代码间增加了间隙
![图片](https://user-images.githubusercontent.com/37981750/91638659-a9c21a00-ea43-11ea-9717-143d68984fe3.png)

颜色更改为 HEX 格式，解决了 `rgba` 属性在导出 pdf 时候透明度丢失问题。
![图片](https://user-images.githubusercontent.com/37981750/91638717-0b828400-ea44-11ea-8563-1a28881bbed7.png)

---
有问题欢迎继续提出 issue， 感谢帮忙完善项目~😉
