### ISSUE TITLE
grave accent in outline

### ISSUE THREAD

**Issue by chenlei-yang** [BEATREE/typora-maize-theme#2]
When the title includes a pair of grave accent ( ` ), it will be totally black in the outline.
Like this:
![image](https://user-images.githubusercontent.com/36327350/92988329-0e2db080-f4fd-11ea-85f2-263fa13da9a1.png)

**Comment by BEATREE** [comment]
![图片](https://user-images.githubusercontent.com/37981750/93039007-fe3adb80-f678-11ea-97ea-8ec5040f9dc2.png)
---
感谢帮忙完善主题，也欢迎积极提出 Pr 哦~
