### ISSUE TITLE
draw diagrams 显示不清楚

### ISSUE THREAD

**Issue by zizicheng** [BEATREE/typora-maize-theme#3]
```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```
这段语言在此主题下显示如下：
![image](https://user-images.githubusercontent.com/17800352/93667387-1024e000-fab8-11ea-81c3-96dc804dfaef.png)

在自带的 github 主题如下：
![image](https://user-images.githubusercontent.com/17800352/93667421-44000580-fab8-11ea-94cd-2e3a2cff1ec0.png)

其它画图语言也有类似问题，也有完全显示正常的

查看了下[样式写作文档](https://theme.typora.io/doc/Write-Custom-Theme/)，发现调整 diagrams 的 background 和 color 颜色即可
/*添加到 maize.css*/
pre[lang='sequence'],
pre[lang='flow'],
pre[lang='mermaid']
 {
	backgorund: #ffffff;
	color: #333333;
}

所以你应该是忘记给 diagrams 添加样式了?

**Comment by BEATREE** [comment]
谢谢建议，正在对 Maize 的样式表格式进行调整，之后会上传更新

**Comment by BEATREE** [comment]
已增加样式，修复问题
