### ISSUE TITLE
It's too slow to download the files of this theme

### ISSUE THREAD

**Issue by xv-feng** [BEATREE/typora-maize-theme#4]
虽然这个主题不大，可为什么下载起来这么慢啊，几kb几kb的下，下到一般就中断了。
有没有人教一下小白

**Comment by BEATREE** [comment]
github 下载速度慢，应该是区域与服务器的原因；建议直接使用 `git clone https://github.com/BEATREE/typora-maize-theme.git` 下载到本地，再删除项目中的非必要文件只保留`maize.css` 与 `maize` 文件夹即可
